### ISSUE TITLE
CMU MOSEI Dataset : old processed data

### ISSUE THREAD

**Issue by johanattia** [A2Zadeh/CMU-MultimodalSDK#101]
Hi, 

I am currently working on speech emotion recognition with old processed CMU MOSEI for now. So I only use audio inputs with shape (20, 74). 

1. About outputs : outputs (y_train, y_valid, y_test) are in [-3, 5] and seem to be continuous values. Looking closely at the unique values, we observe non-continuous but discrete values encoded in this interval which are : 
{-9/3, -8/3, -7/3, -6/3, -5/3, -4/3, -3/3, -2/3, -1/3, 0, 1/3, 2/3, 3/3, 4/3, 5/3, 6/3, 7/3, 8/3, 9/3, 10/3, 11/3, 15/3}.
So, there are 22 distinct outputs following a well-defined order. What are they ? Sentiments ? Emotions ? What precisely do these values represent ? 

2. About audio inputs : audio inputs have shape (20, 74).  What are they ? MFCCs ? Other ? 

3. About audio processing : What is exact processing applied to audio signal ? Have you a python script showing that ? What are packages used ? Librosa ? Scipy ? Others ?

Thank you

**Comment by A2Zadeh** [comment]
Hello @johanattia,

Great questions! Let me answer in the same order.

1. You can trim all the values higher than 9/3 since they are results of 4 annotations (as opposed to 3). AMT has a weird system which we were not aware at that point in time. Sometimes you get more annotations than you want. So it should be 10/4, 11/4 and 15/4. The distinct values are considered a spectrum of how annotators answered sentiment values. 

2. 74 is the features extracted using COVAREP: The dimensions are as follows. 

F0
VUV
NAQ
QOQ
H1H2
PSP
MDQ
peakSlope
Rd
Rd_conf
creak
MCEP_0
MCEP_1
MCEP_2
MCEP_3
MCEP_4
MCEP_5
MCEP_6
MCEP_7
MCEP_8
MCEP_9
MCEP_10
MCEP_11
MCEP_12
MCEP_13
MCEP_14
MCEP_15
MCEP_16
MCEP_17
MCEP_18
MCEP_19
MCEP_20
MCEP_21
MCEP_22
MCEP_23
MCEP_24
HMPDM_0
HMPDM_1
HMPDM_2
HMPDM_3
HMPDM_4
HMPDM_5
HMPDM_6
HMPDM_7
HMPDM_8
HMPDM_9
HMPDM_10
HMPDM_11
HMPDM_12
HMPDM_13
HMPDM_14
HMPDM_15
HMPDM_16
HMPDM_17
HMPDM_18
HMPDM_19
HMPDM_20
HMPDM_21
HMPDM_22
HMPDM_23
HMPDM_24
HMPDD_0
HMPDD_1
HMPDD_2
HMPDD_3
HMPDD_4
HMPDD_5
HMPDD_6
HMPDD_7
HMPDD_8
HMPDD_9
HMPDD_10
HMPDD_11
HMPDD_12

3. You can check out COVAREP for this purpose: https://github.com/covarep/covarep

**Comment by johanattia** [comment]
Thank you @A2Zadeh for these useful informations !

**Comment by A2Zadeh** [comment]
@johanattia happy to help! Good luck with your experiments and let me know if you had any other questions.
