### ISSUE TITLE
Feature extraction for videos

### ISSUE THREAD

**Issue by srikarplus** [A2Zadeh/CMU-MultimodalSDK#114]
HI @A2Zadeh,

I see that the videos in the MOSI dataset have 47 extracted features. I have read in a related paper that OpenFace and OpenSmile were used to extract those features. Can you please tell some details about what those features are ?
To give a little bit of context I have trained a model on MOSI and want to input my own data to predict the sentiments.

Thanks in advance.

**Comment by A2Zadeh** [comment]
Hello @srikarplus,

Yeah, that should be possible. You have to run OpenFace and OpenSmile on your own data, put it in computational sequences and then run your model on the test. The feature dimensions are being added to the SDK as a standard metadata now so that should help you get things moving. So basically you can start by downloading the MultiComp OpenFace and OpenSmile to start the process.

**Comment by srikarplus** [comment]
Hi @A2Zadeh ,
By when can we expect the next release of SDK ?

**Comment by A2Zadeh** [comment]
@srikarplus Hopefully by the end of the week. This is a busy time for us due to the release of another dataset, but we will do our best. Once released, the new version is 1.0.4.
