### ISSUE TITLE
How to align the csd files first on the basis of segments and then all features aligned at word level per segment?

### ISSUE THREAD

**Issue by krayush07** [A2Zadeh/CMU-MultimodalSDK#121]
Thanks for the dataset and `README`. However, there is still a lot of confusion as to how to accurately read the files for the use case.

How can I get the dataset aligned in the given format:

```
- Video i
     ** Segment s0
          ** Word w0, w1, w2, ..., wLast
     ** Segment s1
          ** Word w0, w1, w2, ..., wLast
     ** ...

     ** Segment sLast
          ** Word w0, w1, w2, ..., wLast
```

Essentially say, I would want to use all non-text features as such but instead re-compute my own text features, I would need segment separation as well need word-aligned non-text features.

Could you please help with the pointers?

**Comment by A2Zadeh** [comment]
Hello @krayush07,

All you need to do is download the words, and the labels, put them in a dataset and align to the labels without any collapse function.

**Comment by krayush07** [comment]
Hi @A2Zadeh 

When I do that, here is what I get:

dataset['words.csd'].data['03bSnISJMiM[0]']['features'] -> of size (8, 1)

dataset['glove_vectors.csd'].data['03bSnISJMiM[0]']['features'] -> of size (7, 300)

Why is there a mismatch in number of tokens? Also, word tokens are: 
 [b'sp']
 [b'anyhow']
 [b'sp']
 [b'it']
 [b'was']
 [b'sp']
 [b'really']
 [b'good']

What does token 'sp' refers to?

**Comment by A2Zadeh** [comment]
The reason you are seeing that is the fact that words are one version ahead of glove and bert. I still to have fix that, but you can extract glove and bert just by the words. Remember to extract BERT after  alignment. Otherwise you will use information beyond a single segment. 'sp' is speech pause (between words if there is a pause). 

In short, neglect the bert and glove in our SDK for now, I will update them later. We just migrated to a new alignment for words and that caused the words to be more accurately aligned.

**Comment by krayush07** [comment]
Okay, I get that. I think this should be updated somewhere in the README so that this doesn't create confusion.

Further, I need to have non-text features for each segment aligned at word level. Right now dataset['FACET 4.1.csd'].data['03bSnISJMiM[0]']['features'] is of (100, 47) dimension. How can it be aligned to word level to get (8, 47) dimensional feature set?

**Comment by A2Zadeh** [comment]
I just removed glove and BERT for now from the SDK until I can fix them with the newest words csd.

You need to align first to words with collapse function specified to what you need (collapse function can also be a pytorch function -say a LSTM- since SDK is differentiable). Then you will have the same frequency for visual as you have for words. Afterwards you align to the labels without the collapse, resulting in 8x47. The only thing is that you have to be careful with the visual features being empty for some words (sometime the face is occluded when talking so a word will have no visual features). You can simply add say zeros as that word's visual features. I suggest using FACET 4.2 or OpenFace 2.0. FACET 4.1 is old features, so you will be fighting an uphill battle for getting good results.

**Comment by krayush07** [comment]
Thanks for the suggestion @A2Zadeh 

`collapse function can also be a pytorch function -say a LSTM- since SDK is differentiable`
This information is new, thanks for this.

Quick question/clarification:
Align to words with collapse -> I presume this is same as: `cmumosi_highlevel.align('glove_vectors', collapse_functions=[myavg])`

So before `align to the labels without the collapse`, I should populate new glove vectors (since words.csd has been updated), is my understanding correct?

**Comment by krayush07** [comment]
Or is it possible to get previous words.csd, so that I can directly get aligned non-text features instead of re-mapping new text features back to formatted `csd`?

**Comment by A2Zadeh** [comment]
Yes, but you will get worse results since some words were not aligned (all of our previous papers use this method). BTW if you are only planning on using old features why not go for the old_processed_data folder?

**Comment by A2Zadeh** [comment]
> Thanks for the suggestion @A2Zadeh
> 
> `collapse function can also be a pytorch function -say a LSTM- since SDK is differentiable`
> This information is new, thanks for this.
> 
> Quick question/clarification:
> Align to words with collapse -> I presume this is same as: `cmumosi_highlevel.align('glove_vectors', collapse_functions=[myavg])`
> 
> So before `align to the labels without the collapse`, I should populate new glove vectors (since words.csd has been updated), is my understanding correct?

Yes. You should extract the glove. If you do that then you can also share it with us :)

**Comment by krayush07** [comment]
The reason I am asking for aligned dataset is that it's too confusing to set up the dataset itself for final consumption.

I was reading through the sample code provided in `create_toy_computation_sequence.py`. How should these `intervals` be ideally populated?

```
compseq[vid_key]["features"] = numpy.random.uniform(low=0, high=1, size=[num_entries, feat_dim])
        # let's assume each video is one minute, hence 60 seconds.
        compseq[vid_key]["intervals"] = numpy.arange(start=0, stop=60 + 0.000001,
                                                     step=60. / ((2 * num_entries) - 1)).reshape([num_entries, 2])

```

**Comment by krayush07** [comment]
@A2Zadeh Any update on this? Can I get at least new `glove.csd`?

**Comment by A2Zadeh** [comment]
@krayush07 unfortunately I am a bit tight on time now. If you really need the glove vectors, I highly suggest extracting them from the glove directly. glove comes as a text file which should be easy to parse and extract. 

So basically every piece of information has a start and end. So frame 0 starts from 0.0 to 0.033 seconds (in fact that is how the frames are shown on the screen - start from 0 and keep until 0.033 for 30fps). Then for that interval you may have some features extracted like action units. 

In general we don't provide aligned features to encourage community to explore new alignment techniques and new features. We use this SDK for our internal usage and we never use preprocessed alignment. Each project/student have their own alignment strategies and dump their own csds using their desired strategy. Hope this helps.
