### ISSUE TITLE
specific feature size of MOSEI dataset?

### ISSUE THREAD

**Issue by convman** [A2Zadeh/CMU-MultimodalSDK#132]
video_train = h5py.File("data/video_train.h5","r")
video_train = np.array(video_train.get('d1'))
video_train.shape

This code outputs shape of video_train as (15290, 20, 35). similarly other .h5 files have shape of type (_,20,_). What does this "20" in each size denotes.
Does this 20 represent any specific thing OR features are just reshaped to have 2nd dimension as 20?

**Comment by A2Zadeh** [comment]
@convman I think 20 means the number of words in the training instance 15290 was 20. If I am not mistaken 35 means the FACET dimensions. Does 35 change for other files? Sorry it has been a year and some months since I worked with the old version of SDK. 

I suggest using the newest version of the SDK. We constantly update the descriptors and maintain the datasets in the newest state. It is of course optional, so feel free to use the old one :)

**Comment by convman** [comment]
Thanks for the help!
audio_train.h5 - (15290, 20, 74)
video_train.h5 - (15290, 20, 35)
text_train_emb.h5 - (15290, 20, 300)
I am a new to this dataset...how " 20 means the number of words" relates to video (image) data? Is it due to word-frame alignment?

**Comment by A2Zadeh** [comment]
@convman Of course, happy to help! Yes, that means continuous alignment which we used words as reference so basically word alignment. We allow each sentence to have 20 words max. 300 is the glove dimensions. 35 is the video and 74 is the audio. Let me know if you have any other questions. If you are interested in getting new state of the art on CMU-MOSEI please have a look at our newest RAVEN approach to see how to improve word alignment.
