### ISSUE TITLE
How to download cmu_mosi without SDK?

### ISSUE THREAD

**Issue by Whisht** [A2Zadeh/CMU-MultimodalSDK#133]
I used the SDK to download the dataset, alwyas getting a wrong connection error. So I use other software(IDM) to download the dataset. But I just found several `.csd` file.
```python
CMU_MOSI_ModifiedTimCMU_MOSI_TimestampedWords.csd
CMU_MOSI_TimestampedPhones.csd
CMU_MOSI_VisualFacet_4.1.csd
CMU_MOSI_OpenSmile_EB10.csd
CMU_MOSI_openSMILE_IS09.csd
CMU_MOSI_OpenFace2.csd
CMU_MOSI_COVAREP.csd
CMU_MOSI_Opinion_Labels.csd
```
Missing `CMU_MOSI_ModifiedTimestampedWords.csd`, So I cannot load the dataset with `mmdatasdk.mmdataset()`.

Could you please tell me where to download this `.csd` file?

**Comment by A2Zadeh** [comment]
Yeah of course. Here is the link to download all the CMU-MOSI. Try to get it with the SDK, because then you can always easily pull SDK again and get newest features. Anyways, here is the link to get all of CMU-MOSI csds: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/

BTW, it is CMU_MOSI_TimestampedWords.csd but they root name of the computational sequence is CMU_MOSI_ModifiedTimestampedWords. Just a small name change to make it known that this is the newest most accurate word timestamps. Maybe I should change that to CMU_MOSI_TimestampedWords to avoid confusion. What do you think ;)?

**Comment by Whisht** [comment]
Thanks a lot! I wrote some testing code according to the tutorial in `starter_full_tutorial_by_zhun_liu.py`. It seems that the `.csd` files version differs froms the current one which do not contain `CMU_MOSI_ModifiedTimestampedWords.csd`.
![image](https://user-images.githubusercontent.com/16497652/59663242-2a9b4a00-91e1-11e9-9378-2184972629f8.png)

**Comment by A2Zadeh** [comment]
@Whisht Ah ok I see. It's just the file name that is different. The rest should work just fine. BTW, we took BERT and glove (word vectors) down for maintenance. Those will not be available for now, but I will try to update it this weekend. In any case you should be able to continue the tutorial with just the file name change of the ModifiedTimestampedWords.csd to TimestampedWords.csd. Let me know if anything else came up.

**Comment by Whisht** [comment]
Thanks for your help. Have a nice day~
