### ISSUE TITLE
CMU-MOSEI dataset labels for raw data

### ISSUE THREAD

**Issue by anciubotaru** [A2Zadeh/CMU-MultimodalSDK#142]
Dear Amir,

I would like to extract my own features from the raw MOSEI **video** data downloaded from here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/.
I saw that there are segmented videos, but also the full ones. With respect to the labels for both emotions and sentiments, are they for the segmented videos or for the full ones?
Also, is it normal that certain video segments to be fully black? For example this one: ZzL2sHtTWRc has some segments that are fully black.

**Comment by anciubotaru** [comment]
Also, can I have access to the raw data and labels from the SDK?

**Comment by A2Zadeh** [comment]
@anciubotaru, happy to help. The sentiment scores are for the segmented (or better yet, sentences from the full video). Not all the sentences will have labels since CMU-MOSEI is actually semi-supervised. However, ~23,500 should have it. Raw data and labels are provided in CSD files, similar to example demonstrated using CMU-MOSI in here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/word_level_align.py and https://github.com/Justin1904/CMU-MultimodalSDK-Tutorials. You can get all the computational sequences for CMU-MOSEI from here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI/cmu_mosei.py. You also have the option of getting the original processed data (which had some issues for COVAREP, but could work well for debugging and training your model before using the newest features). Furthermore, the labels and features are also available in the actual raw dataset zip file. Please let me know if you had any other questions.

**Comment by anciubotaru** [comment]
@A2Zadeh  thanks for the fast reply. I highly appreciate it. It was very useful.
I've been looking into CMU_MOSEI_LabelsEmotion.csd file and I would like you to confirm if the "features" having the dimension N x 6 represent N video segments labeled with [happy,sad,anger,surprise,disgust,fear]. I assume that the features are represented as floats because they were created by more than one annotator. Am I right?

**Comment by A2Zadeh** [comment]
You are correct. Nx6 represents emotions and Nx2 represents beginning and end of sentences within the video. You also have the correct ordering for emotions.

**Comment by liufh3** [comment]
Hi,

I have opened CMU_MOSEI_LabelsEmotion.csd file and found there are more than one emotion for some segmented videos. Could you confirm I am right?

**Comment by A2Zadeh** [comment]
Hello @liufh3, you are right. CMU-MOSEI extends beyond single emotion annotations (in reality there may be sadness and anger at the same time). Therefore, we annotate an intensity for each of the emotions, as opposed to going for the dominant emotion in the clip. If you want the dominant emotion, my suggestion is picking the one with highest intensity. Does that answer your question?

**Comment by liufh3** [comment]
Yes, thanks for reply, it is very helpful!

**Comment by A2Zadeh** [comment]
@liufh3 You are very welcome. Good luck with your experiments.

**Comment by FelixFox** [comment]
@anciubotaru Hello! It seems you succeed in getting the features (emotion labels). How did you get them?  I've created an issue ( https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/144 ) but it's still unresolved. 

Thank you!

**Comment by AndreyGalitsin** [comment]
Hello everyone! Tell me please, how can I download the CMU_MOSEI_LabelsEmotion.csd file ?
