### ISSUE TITLE
How is the phoneme sequence in MOSI generated

### ISSUE THREAD

**Issue by CodePothunter** [A2Zadeh/CMU-MultimodalSDK#147]
There is a phone sequence in the MOSI dataset. Can anyone tell how are they generated and where to achieve the full vocabulary?

**Comment by A2Zadeh** [comment]
@CodePothunter good question. The phoneme are done based on forced alignment between the audio and text using P2FA. The full vocabulary is accessible through the raw files here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip

Let me know if you have any other questions.

**Comment by CodePothunter** [comment]
@A2Zadeh  Thank you. I notice that the dataset paper states that the words are transcript according to the audio, and aligned using P2FA. Does it mean that the phonemes are side-product of this alignment process? I don't really get it.

**Comment by A2Zadeh** [comment]
@CodePothunter Yes. the phonemes are actually the basis of the alignment with P2FA. First the phonemes are detected and then boundaries of words are determined using warping methods (e.g. DTW (Dynamic Time Warping)).

**Comment by CodePothunter** [comment]
P2FA says: _Forced alignment helps to align linguistic units (e.g., phoneme or words) with the corresponding sound file._ So we still need to feed phoneme sequence into it?

**Comment by CodePothunter** [comment]
![image](https://user-images.githubusercontent.com/7928631/62556633-e4409e00-b8a7-11e9-879c-9e549f5f3bef.png)

**Comment by A2Zadeh** [comment]
@CodePothunter We just need the word sequence and the audio file. Word to phoneme dictionary maps the words to phonemes. Inside P2FA there is a word to phoneme dictionary.

**Comment by A2Zadeh** [comment]
Closed due to inactivity. I assume the problem is solved.

**Comment by AnilRahate** [comment]
Hi Amir, 
1. I would like to know how video is aligned with audio and word? Is it just matching intervals of audio file with video file?
2. One has to take frames from a video and capture facial (visual) features. How many frames were captured per interval (word)
3. How do I find meta data (features) for Audio and visual modality for MOSI
4. I am curious, what was accuracy when alignment is done at sentence level instead of word (as provided in segments in raw MOSI data)

Thanks.
