### ISSUE TITLE
@A2Zadeh i am still not able to find the labels for the raw files. I am looking for labels for the transcript files present here: CMU_MOSEI\Raw\Transcript\Segmented\Combined.

### ISSUE THREAD

**Issue by shamanez** [A2Zadeh/CMU-MultimodalSDK#169]
@A2Zadeh i am still not able to find the labels for the raw files. I am looking for labels for the transcript files present here: CMU_MOSEI\Raw\Transcript\Segmented\Combined.
I am interested in both the emotion labels as well as the sentiment analysis labels. Could you help me find them please.

_Originally posted by @tapan1911 in https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/154#issuecomment-549555263_

**Comment by A2Zadeh** [comment]
@shamanez I am sorry to hear that you are having some trouble navigating through the SDK and raw files of the CMU-MOSEI. At the same time I am very grateful for your in-depth analysis of the dataset structure and all the issues you were able to find. If it helps, I am happy to Skype with you and solve these issues. Please let me know if that would be helpful to you, and if so, please send me an email so we can start things off. 

Otherwise, I will be happy to continue answering your questions here. Please let me know.

**Comment by shamanez** [comment]
yeah. I would love to help you to create a clean multimodal row dataset from the given CMU-MOSEI labels. For my understanding, this should basically contain audio, video and text folder. Then a label file for each example. For that, I can also add Roberta/XL-NET sentence level embeddings. I actually managed to go through labels given in SDK and map them to row videos. I would also love to share all my codes with you. 

**But before finalizing I would love to have a skype chat with you. When you will be free and how can I contact you?** 

my personal email - shamane@ahlab.org

**Comment by A2Zadeh** [comment]
Hello @shamanez. Thank you for accepting to talk over Skype. I will be in touch tomorrow to set a meeting time.

**Comment by shamanez** [comment]
Thank you for your response. Please  let me know your available time.
