### ISSUE TITLE
The VAD Value of IEMOCAP data

### ISSUE THREAD

**Issue by Imorton-zd** [A2Zadeh/CMU-MultimodalSDK#174]
@A2Zadeh  Thanks for your great project in multi-modal learning.. Would you please public the target value of processed IEMOCAP data in SDK, i.e., Valence, Arousal and Dominance? If possible, could the processed samples be sorted as each dialogue with a video id and an utterance id?

**Comment by A2Zadeh** [comment]
Hi @Imorton-zd,

The VAD values should be in the preprocessed data on the immortal server. As for the video IDs please refer to [this](https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/185). Sadly, we don't have the correspondance to ids since the IEMOCAP dataset was processed using SDK V0. It is all correctly done, but just not invertible to the actual ids.
