### ISSUE TITLE
CMU MOSEI speaker information

### ISSUE THREAD

**Issue by vlad-filin** [A2Zadeh/CMU-MultimodalSDK#180]
Hi! 

Thank you for your work!

 I have a question about obtaining information of speaker for each audio. In [the article about dataset](https://www.ml.cmu.edu/research/dap-papers/S18/dap-liang-paul-pu.pdf) it was highlighted that dataset contains 1000 speakers and  equal number of male/female speakers (57.2% male and 42.8% female). Also in issue #71 speaker id information is said to exist and it is possible to share it.

Is it possible to get speaker id (number from 1 to 1000) and gender information for each sample of dataset (e.g. for each wav file/ video)?

I coudn't find a way for finding this information  using SDK or  exploring [raw data](immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip).

**Comment by A2Zadeh** [comment]
Hi @vlad-filin,

Sorry for the late reply. I believe we have that information somewhere, but I cannot find where it was. Is this still something you are interested in?

**Comment by vlad-filin** [comment]
Hi, @A2Zadeh 

Unfortunately, without speaker_id this dataset is not relevant for my tasks.
Thank you for your time and work!

**Comment by wikong** [comment]
Hi @A2Zadeh 
I would have been interested in speaker labels also, in order to avoid bias in the evaluation process : the goal is to ensure  that speakers in an evaluation split have not been seen during the training stage. 
Could you recover the information or should we consider it as definitely lost?

Alternatively, do you propose a split for train and test, so that users could have fully comparable evaluations ?

Thx in advance
