### ISSUE TITLE
Question about how to process text data

### ISSUE THREAD

**Issue by EmptyMoon-hub** [A2Zadeh/CMU-MultimodalSDK#184]
Hi Amir, I wonder how you handle text data,  Glove model or Bert model???

**Comment by A2Zadeh** [comment]
Hi @EmptyMoon-hub. Depends on the paper :). We have done both so far. Usually we use glove since no fine-tuning is needed. Also if working on multimodal data, focus is mostly on fusion and getting the modalities to work together. Naturally we would expect the unimodal improvements would improve the multimodal one as well. There are some papers on CMU-MOS(E)I that use BERT.

**Comment by EmptyMoon-hub** [comment]
Thank you very much for your quick reply.
And I would like to know if the aligned and non-aligned data in the processed data folder is implemented using the glove model.

**Comment by A2Zadeh** [comment]
@EmptyMoon-hub Those are glove vectors. Usually, the BERT is not used to extract features, but rather mostly as a "fine-tuning" framework. So it is a bit more complicated to include BERT.

**Comment by EmptyMoon-hub** [comment]
Ok, thanks again for your reply！！！
