### ISSUE TITLE
Question about the "id" of IEMOCAP

### ISSUE THREAD

**Issue by EmptyMoon-hub** [A2Zadeh/CMU-MultimodalSDK#185]
Hi, I'm sorry to bother you again.
But I find that "iemocap_data.pkl" doesn't have "id" while all the other datasets do.
Is this a bug? 
Or the "data.zip" includes “id”？

**Comment by A2Zadeh** [comment]
Hi @EmptyMoon-hub,

Please see [this](https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/189). Since IEMOCAP is not a publicly available dataset (i.e. you have to ask permission), we did not go down the road of putting things in .csd format. That communication was never made with USC. If I see this issue raised a few more times, I will prioritize addressing it. Nonetheless, the extracted features from raw IEMOCAP should help you put everything in .csd format and do a fresh alignment which allows for the ID to also be there. If you do the csd conversion, please share it with me so I can share with everyone.
