### ISSUE TITLE
problems with CMU-MOSEI labels and intervals

### ISSUE THREAD

**Issue by xonecell** [A2Zadeh/CMU-MultimodalSDK#198]
Hi there, I am reading the publication for CMU-MOSEI and i'm having some difficulty understanding the labels. 

1.) In the paper, there are two bar chart graphs, one for sentiment and other one for emotions. I would like to know how can I get the left bar chart. I got the SDK working and from what I understand, there are values: sentiment, happy, sad, anger, surprise, disgust, fear. Is the sentiment column the one that generated that bar chart? I see 5 bars in left graph, but the paper says that sentiment values are from -3 to 3, so shouldn't there be 7 bars then?
![image](https://user-images.githubusercontent.com/66010601/83009157-f4845e00-a01e-11ea-801f-7e08f171bee4.png)
![image](https://user-images.githubusercontent.com/66010601/83009494-85f3d000-a01f-11ea-85ac-47af55b7b20f.png)

2.) Also, when I extracted values from CMU_MOSEI_All_Labels there is a key "intervals", I assume they are in miliseconds, but some of the values are negative, is it okay if I clamp them to zero? 
```
-0.41768707483
-0.487528344671
-0.487528344671
-0.248072562358
-0.487528344671
-0.487528344671
-0.487528344671
-0.487528344671
```

3.) Some labels are missing. I'm using raw data, because our pipeline is quite different and the way i'm getting labels is looking at video filename and the look it up in labels extracted from SDK. Some videos have no labels (total of 545), why is that?
[bad.txt](https://github.com/A2Zadeh/CMU-MultimodalSDK/files/4688464/bad.txt)

**Comment by A2Zadeh** [comment]
Hi @xonecell 

You are right, there should be 7, however, to be consistent with previous works, we create 5 out of those 7. Specifically, text-only sentiment analysis seems to be focusing on the 5 class. You can find the formula here: https://github.com/A2Zadeh/CMU-MultimodalSDK/tree/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI

Yeah interavals can be negative. They are actually seconds with fractions. The only reason for intervals being negative (which is worst case -0.5) is that we pad the sentence by 0.5 to compensate for forced alignment variations. If sentence start at the beginning of the video then the first sentence will have an interval of -0.5. This really does not change anything since overall, the alignment logic is based on values and boundary cases taken care of. 

Yes, CMU-MOSEI is a semi supervised dataset. We have released around ~3800 videos, from which 500 have no labels. We plan to extend this dataset to much larger in the future. 

Hope this answered your questions. Please send me any other issues you may have. Best of luck with your experiments.

**Comment by xonecell** [comment]
Thank you for the quick response, all questions answered!

**Comment by xonecell** [comment]
Hey, thank you for previous answers, I have a follow up question.
When I look at labeled emotions in CMU-MOSEI dataset, there is no neutral emotion.
There are however samples labeled like [0, 0, 0, 0, 0, 0, 0] where all emotions are zeros.
My question then is - does this mean that this sample is unlabeled or if all emotions are zeros, this means that the emotion is neutral?
Thank you!

**Comment by A2Zadeh** [comment]
Hi @xonecell. That means the 6 basic emotions are not present. I know that in some datasets the neutral is different than not having any of the 6 emotions. Say one could be "jealous" if that was an emotion, or "grumpy". The list of such labels could go on forever. In short, we followed the NLP convention mostly, but affect datasets (e.g. IEMOCAP) do tend to differentiate neutral from not having emotions. We will consider that in the next version of MOSEI, with possibly larger dataset and more annotators per video.

**Comment by xonecell** [comment]
Ok, thanks a lot, I will try to run some tests where if no emotions are present, I will assume it is neutral. Thanks again!
