### ISSUE TITLE
About mosei feature extraction

### ISSUE THREAD

**Issue by KuzmaNg** [A2Zadeh/CMU-MultimodalSDK#203]
Hi, there! I wanna some details on the feature extraction. Why choose the tools like Facet, openSmile, OpenFace, COVAREP? How much time would it take to re-extract the features with the raw data?
Thank you.

**Comment by A2Zadeh** [comment]
Hi @KuzmaNg. Apologies for the late reply, I was a bit busy with life stuff. The tools are chosen due to a few reasons:

1. OpenFace 2.0 is pretty much SOTA on landmark detection and AU detection, so that is good for us. FACET also has shown to present some interesting features. Both are good for the highlevel feature extraction. 

2. Acoustic signal processing is mostly done using engineered features such as MFCC. So there, both COVAREP and OpenSmile are helpful. 

The time to extract is reasonable (almost 1-1 with video length). But it is certainly not real-time (except for OpenFace).
