### ISSUE TITLE
COVAREP features' dimensions

### ISSUE THREAD

**Issue by Ighina** [A2Zadeh/CMU-MultimodalSDK#208]
Hello,

I was looking at the metadata for COVAREP on MOSEI, but it looks like there is no description for the dimensions of the features. Would it be possible to know which dimension relate to which statistic or, alternatively, could you point to the COVAREP file you used to extract the features and the parameters you used?

Thanks,
Iacopo

**Comment by A2Zadeh** [comment]
Hi @Ighina. Did you have a look at the metadata of the csd files? You can access using csdhandle.metadata

Otherwise, this is the dimension names:

["F0","VUV","NAQ","QOQ","H1H2","PSP","MDQ","peakSlope","Rd","Rd_conf","creak","MCEP_0","MCEP_1","MCEP_2","MCEP_3","MCEP_4","MCEP_5","MCEP_6","MCEP_7","MCEP_8","MCEP_9","MCEP_10","MCEP_11","MCEP_12","MCEP_13","MCEP_14","MCEP_15","MCEP_16","MCEP_17","MCEP_18","MCEP_19","MCEP_20","MCEP_21","MCEP_22","MCEP_23","MCEP_24","HMPDM_0","HMPDM_1","HMPDM_2","HMPDM_3","HMPDM_4","HMPDM_5","HMPDM_6","HMPDM_7","HMPDM_8","HMPDM_9","HMPDM_10","HMPDM_11","HMPDM_12","HMPDM_13","HMPDM_14","HMPDM_15","HMPDM_16","HMPDM_17","HMPDM_18","HMPDM_19","HMPDM_20","HMPDM_21","HMPDM_22","HMPDM_23","HMPDM_24","HMPDD_0","HMPDD_1","HMPDD_2","HMPDD_3","HMPDD_4","HMPDD_5","HMPDD_6","HMPDD_7","HMPDD_8","HMPDD_9","HMPDD_10","HMPDD_11","HMPDD_12"]
