### ISSUE TITLE
list index out of range trying to download the dataset

### ISSUE THREAD

**Issue by SG-lab** [A2Zadeh/CMU-MultimodalSDK#212]
Dear Sir ZADEH,

I am trying to follow your git hub instructions to download the data provided by mmdatasdk.cmu_mosi.highlevel dictionary. In fact, I find an issue running the two following lines on spyder :

>>> from mmsdk import mmdatasdk
>>> cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')

This is the error I get :

  File "C:\Users\username\CMU-MultimodalSDK\mmsdk\mmdatasdk\computational_sequence\download_ops.py", line 15, in read_URL
    if os.path.isdir(destination.rsplit(os.sep,1)[-2]) is False:

IndexError: list index out of range

Thank's for the attention you'll give to this message

**Comment by A2Zadeh** [comment]
Hi @SG-lab. That is odd. Are you running the mosi alignment code?

**Comment by SG-lab** [comment]
Hello !
Thank's for answering. I didn't run anything except the two previous lines as shown on the github instructions. Besides, I don't know what you call "mosi alignment code", is it the process_mosi.py file ? 
If it is the process_mosi.py file, here is what I get once I run it : (I use windows os and work on spyder module of anaconda)

 File "C:\Users\username\CMU-MultimodalSDK\mmsdk\mmdatasdk\log\log.py", line 95, in error
    raise errorType(msgstring)

RuntimeError: Dataset folder does not exist ...

**Comment by A2Zadeh** [comment]
@SG-lab, oh I see you are using windows? I haven't tested the SDK in the Windows OS. Probably I should :). Can you use linux/mac?

**Comment by SG-lab** [comment]
I can't at the moment. I will try to install a virtual machine then and let you know if it's ok for you.
Thank you for your availability

**Comment by A2Zadeh** [comment]
@SG-lab alternatively, you can download CMU-MOSI pre-aligned. It can be found here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosi/

**Comment by SG-lab** [comment]
Ok I see, the data is already configured to straightly train the AI model in the seq_length_20 repository. There are only some things I still don't get if it's ok for you to answer :
-What is the difference between valid data and the others ? Are we not supposed to have train sets and test sets only ?
-Why do we need to include the dimensions from acoustic and visual (with fs_mask file) though, since the data is already -structured the  the seq_length_20 repository ? 
-What is, the seq_length_50 repository, for ? 
(sorry about those questions, I'm trying to understand ^^" )

**Comment by A2Zadeh** [comment]
@SG-lab no worries, happy to help!

-What is the difference between valid data and the others ? Are we not supposed to have train sets and test sets only ?
-- We use the validation data to make sure we are not picking models that work best on the test set (test overfitting)
-Why do we need to include the dimensions from acoustic and visual (with fs_mask file) though, since the data is already -structured the the seq_length_20 repository ?
-- We pick those dimensions since they have been most useful. You can use the entire visual and acoustic. 
-What is, the seq_length_50 repository, for ?
-- The same as sequence = 20 except, the sequence length is 50

**Comment by SG-lab** [comment]
How can [0, 2, 5, 10, 11, 12, 14, 17, 20, 21, 22, 24, 25, 29, 30, 31, 32, 36, 37, 40] be the indices for visual since the first 300 are the word vectors and those indices are all less than 300 ?

**Comment by A2Zadeh** [comment]
@SG-lab, those are the dimensions chosen from the visual and acoustic features. Visual is around ~49 features and acoustic is 72. Therefore those are the indices. Subsequently, those indices add up to 25 (visual and acoustic), and the input space of CMU-MOSI is therefore 325 in the old preprocessed data.

**Comment by SG-lab** [comment]
Ok very clear, thank you so much :)

**Comment by A2Zadeh** [comment]
@SG-lab Happy to help! Good luck with your experiments!

**Comment by npurson** [comment]
It is because that the `os.sep` under Windows is actually `\\` rather than `/` under Linux.
The solution is simply replace the `os.sep` with `/` in the following 2 pieces of code:
1. `mmsdk\mmdatasdk\computational_sequence\download_ops.py`, line 15:
```python
if os.path.isdir(destination.rsplit(os.sep, 1)[-2]) is False:
    os.mkdir(destination.rsplit(os.sep, 1)[-2])
```
2. `mmsdk\mmdatasdk\computational_sequence\computational_sequence.py`, line 70:
```python
elif '.csd' not in destination:
    destination=os.path.join(destination, resource.split(os.sep)[-1])
```
