### ISSUE TITLE
labels in the processed raw dataset of CMU MOSEI

### ISSUE THREAD

**Issue by SG-lab** [A2Zadeh/CMU-MultimodalSDK#218]
In the processed CMU MOSEI raw dataset, we find that some ouputs for emotion are greater than 3. That's a nonsense compared to what is explained. We should find the outputs vectors with each coordinate being between 0 and 3 and I found at least one value being 3.3333 and another being equal to 4.333. Is it normal @A2Zadeh ???

**Comment by A2Zadeh** [comment]
@SG-lab, yes and no. That was due to a bug in AMT. What we expected from AMT is to have the sentences annotated exactly 3 times. Therefore, sum of all 3 annotations for a sentence divided by 3, is the average. AMT somehow annotated few sentences more than that (4 or 5 times). Therefore, for a small set of sentences, the original method of averaging ended up generating values that were bigger than 3. This was of course an honest mistake, and due to a bug in AMT system. It only affects a few sentences in the old preprocessed data. You can clamp those values to 3, or use the latest version of the data here: http://immortal.multicomp.cs.cmu.edu/ACL20Challenge/tensors.pkl

**Comment by SG-lab** [comment]
Thank's again ! @A2Zadeh :D

**Comment by SG-lab** [comment]
@A2Zadeh , the data you provided (http://immortal.multicomp.cs.cmu.edu/ACL20Challenge/tensors.pkl) contain 7 emotions outputs. The old preprocessed data had 6 for the following emotions in the respect of the coordinates order an one vector : Anger, Disgust, Fear, Happy, Sad, Surprise. 
What are then the 7 emotions with their respective order on one output vector of tensor.pkl ?

**Comment by A2Zadeh** [comment]
Sure, 

`dimensions=["sentiment","happy","sad","anger","surprise","disgust","fear"]`

**Comment by SG-lab** [comment]
Ok thank's, so one of the outputs si for the sentiment intensity (which is between -3 et +3 if I am not wrong)). Is there any trouble if I delete the sentiment coordinate ? I would like to first try a neural model to predict only the emotion (and not sentiment intensity).  In that way, I would train the model with the same inputs X, with only 6 outputs for the emotions in spite of 7 prior outputs ?
