### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Ludusss** [A2Zadeh/CMU-MultimodalSDK#340]
"Forbidden
You don't have permission to access /ACL20Challenge/ on this server."

I'm currently getting this error when trying to access the data online.

**Comment by yandun72** [comment]
me too;
please help me

**Comment by marco-hmc** [comment]
me too.

**Comment by Byshev333** [comment]
me too.

**Comment by Luckypolo2** [comment]
same

**Comment by A2Zadeh** [comment]
Hey folks,

There seems to have been an issue with the hard drive hosting the data. I am no longer at CMU, but I do have backups of the data and I can host it somewhere else. This might take a while because I'll have to communicate properly with CMU about where to host it so they're cool with it too. Stay tuned, this will max take 10 days.

**Comment by ayesha-119** [comment]
I'm getting the same error

**Comment by LetianLee** [comment]
Same here. keep watching this issue

**Comment by ayesha-119** [comment]
> I'm getting the same error



> 

does this issue get fixed?

**Comment by ayesha-119** [comment]
> Hey folks,
> 
> There seems to have been an issue with the hard drive hosting the data. I am no longer at CMU, but I do have backups of the data and I can host it somewhere else. This might take a while because I'll have to communicate properly with CMU about where to host it so they're cool with it too. Stay tuned, this will max take 10 days.

does this issue got fixed?

**Comment by joyolee** [comment]
> Hey folks,
> 
> There seems to have been an issue with the hard drive hosting the data. I am no longer at CMU, but I do have backups of the data and I can host it somewhere else. This might take a while because I'll have to communicate properly with CMU about where to host it so they're cool with it too. Stay tuned, this will max take 10 days.

Thanks for your hard work on this stuff. I would ask, is it possible now to have access to the MOSEAS data?

**Comment by DarkAI2021** [comment]
> Hey folks,
> 
> There seems to have been an issue with the hard drive hosting the data. I am no longer at CMU, but I do have backups of the data and I can host it somewhere else. This might take a while because I'll have to communicate properly with CMU about where to host it so they're cool with it too. Stay tuned, this will max take 10 days.

Thanks for your time for consideration and reply. I would also ask if it is possible to access the CMU-MOSEI datasets.

**Comment by pj-kas** [comment]
@A2Zadeh ping

**Comment by Ludusss** [comment]
@A2Zadeh Did you manage to get in touch with CMU?

**Comment by A2Zadeh** [comment]
Folks, some update here. I am currently negotiating with CMU folks to keep the immortal server. The general vibe there seems to be towards decommissioning it, without a solution for what comes next. We have backups, so once we find a server at CMU, we'll be good. I'll keep you posted. 

Problem with putting the datasets through my own means is that it will be a huge legal liability, first they are CMU's intellectual property, and second they require constant awareness due to changing laws around creative commons license and YouTube fair use policy. To put in perspective, even I, as the creator of the datasets, can't use it to train sentiment models outside academia - not even the anonymized features. 

So we're stuck with how fast CMU can resolve the issue on their side.

**Comment by aronnoordhoek** [comment]
@A2Zadeh Any update on this? Looks like it has been a month since  your last message.

**Comment by EchoxShi** [comment]
Any update on this?

**Comment by A2Zadeh** [comment]
There is actually some good news. We are able to keep the immortal server, I just need to make a couple of minor adjustments and we should have it up and running in a week or so.

**Comment by sablea** [comment]
> Any update on this?

**Comment by aronnoordhoek** [comment]
> > Any update on this?
> 

In the meantime I got MOSEI from here

https://github.com/pliang279/MultiBench

**Comment by sablea** [comment]
> > > Any update on this?
> 
> In the meantime I got MOSEI from here
> 
> https://github.com/pliang279/MultiBench

do you know the mosei data from [GoogleDrive](https://drive.google.com/drive/folders/1A_hTmifi824gypelGobgl2M-5Rw9VWHv) is aligned?

**Comment by Wang-shiqi** [comment]
cool!That is partly downloadable now

**Comment by A2Zadeh** [comment]
Folks, everything should be back online. Cheers.

**Comment by fgtoralesch** [comment]
Downloaded successfully cmu_mosi following the readme and currently downloading socialiq. Thanks a lot for the fix!

**Comment by ayesha-119** [comment]
> Downloaded successfully cmu_mosi following the readme and currently downloading socialiq. Thanks a lot for the fix!

I'm still getting the error CMU_MOSI_ModifiedTimeStampWords.csd file not found. 

Did you get that error too?

**Comment by MMirandaM** [comment]
> There is actually some good news. We are able to keep the immortal server, I just need to make a couple of minor adjustments and we should have it up and running in a week or so.

Any update on this?

'http://immortal.multicomp.cs.cmu.edu/raw_datasets/' is available????
