### ISSUE TITLE
Cannot find labels and raw data in MOSEI 

### ISSUE THREAD

**Issue by hsiehjackson** [A2Zadeh/CMU-MultimodalSDK#53]
Thank you for the data you provided. I follow your paper and dataset for a while, but I have some problems for this SDK.
I find some processed features in acoustic, language and visual in the SDK. However, I look forward to deal with the raw data and check labels in every segments on my research.  Will you have any updates recently?

**Comment by XinyuLyu** [comment]
Hello,
I have several questions about MOSEI dataset sdk. I find the codes in readme of CMU-Multimodal SDK only works for the MOSI dataset. I simply change all the 'mosi' to 'mosei' to test if it still works for the MOSEI dataset, for there are no instructions about it in readme.
1. When I use the codes below, it only downloads the CMU_MOSEI_VisualFacet42.csd and  glove_vectors.csd. I think data sets are incomplete
<code>>>>cmumosei_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosei/')</code> 
2. With the codes below, I find there is no attirbute called 'labels' of mmdatasdk.cmu_mosei.labels
<code>>>>cmumosei_highlevel.add_computational_sequence(mmdatasdk.cmu_mosei.labels,'cmumosei/')</code>
3.When call the align functions, I find the process will comes to the error like belows.
<code>>>>cmumosei_highlevel.align('glove_vectors',collapse_functions=[myavg])  </code>
#log
<code>>>>Overall Progress:  30%|▎| 985/3303 [21:31<54:53,  1.42s/ Computational Sequence Overall Progress:  30%|▎| 986/3303    [21:32<55:01,  1.42s/ Computational Sequence Entries]</code>                                                                     
<code>>>Traceback (most recent call last):                | 0/208 [00:00<?, ? Segments/s]</code>
<code>>>>File "<stdin>", line 1, in module </code>
<code>>>>File "/Users/xinyu/CMU-MultimodalSDK/mmsdk/mmdatasdk/dataset/dataset.py", line 58, in align otherseq_key], epsilon)</code> 
<code>>>>File "/Users/xinyu/CMU-MultimodalSDK/mmsdk/mmdatasdk/dataset/dataset.py", line 119, in __intersect_and_copy</code>
 <code>>>>sub = numpy.concatenate([sub_compseq.data[x]["intervals"] for x in relevant_entries], axis=0)
 ValueError: need at least one array to concatenate</code>

Is it just because the SDK does not work for the MOSEI datasets?

**Comment by A2Zadeh** [comment]
Let me look into this issue. Thanks for raising it.

**Comment by songxujing** [comment]
I look forward to deal with the raw data and check labels in every segments on my research.
How to download all  CMU-MOSEI raw data?
Thank you very much! @A2Zadeh @hsiehjackson

**Comment by padisarala** [comment]
You can download MOSEI raw dataset from the following link

http://immortal.multicomp.cs.cmu.edu/

**Comment by kavya-45** [comment]
Duplicate of #THe download has doesn't open please help me to find dataset. Thanks in advance.

**Comment by Cristeen20** [comment]
http://immortal.multicomp.cs.cmu.edu/
The link is not opening for me. Please help me to get the raw dataset. Thanks in advance.

**Comment by Cristeen20** [comment]
> You can download MOSEI raw dataset from the following link
> 
> http://immortal.multicomp.cs.cmu.edu/
The link is not opening for me. Please help me to get the raw dataset. Thanks in advance.
