### ISSUE TITLE
Code for multimodal sentiment analysis with RL

### ISSUE THREAD

**Issue by kushagrajain11** [A2Zadeh/CMU-MultimodalSDK#60]
Hi Amir,
Do you have any plans for making the code for Multimodal Sentiment Analysis with Word-Level Fusion and Reinforcement learning available?
Thanks

**Comment by A2Zadeh** [comment]
@kushagrajain11 I should be able to ask around. I am not the first author on that paper so it might be harder for me to get my hand on the code. I will do my best though :)

**Comment by kushagrajain11** [comment]
@A2Zadeh That would be really helpful, thanks! Whom would you suggest I contact if I'm looking for the implementation details and any other queries regarding the paper?

**Comment by A2Zadeh** [comment]
@kushagrajain11 you should potentially contact Minghai Chen for that. I will also ask around for the code. It may take me some time.

**Comment by kushagrajain11** [comment]
@A2Zadeh thanks for the help!
I have a few more questions regarding mmsdk-  

1. What do the keys represent in aligned data? I downloaded all the computational sequences and have aligned my data by running the following code - 
`dataset=mmdatasdk.mmdataset('cmumosi/')'
`dataset.align('glove_vectors',collapse_functions=myavg)`
`dataset.align('Opinion Segment Labels')`

dataset is now a dictionary containing (facet, opensmile, opinion_labels, glove_vectors, words, phonemes) each of which is a computational sequence.

Each of the 6 computational sequences has the following keys - 
`wMbj6ajWbic[254][0]`
`BvYR0L6f2Ig[108][0]`
`2iD-tVS8NPw[443][0]`
`2WGyTLYerpo[391][0]`
`OQvJTdtJ2H4[88][0]`
`wMbj6ajWbic[658][0]`

There are 35000+ such keys

what do these dimensions - [254][0] , [108][0] etc in front of the video id represent?

2. is this aligned data suitable for implementing "multimodal sentiment analysis with RL"? Or did you use another data format for that. Can you tell the input data format if possible because from the paper it is not clear.

**Comment by kushagrajain11** [comment]
@A2Zadeh thanks for the help!
I have a few more questions regarding mmsdk-

1. What do the keys represent in aligned data? I downloaded all the computational sequences and have aligned my data by running the following code -
dataset=mmdatasdk.mmdataset('cmumosi/')
dataset.align('glove_vectors',collapse_functions=myavg)
dataset.align('Opinion Segment Labels')

dataset is now a dictionary containing (facet, opensmile, opinion_labels, glove_vectors, words, phonemes) each of which is a computational sequence.

Each of the 6 computational sequences has the following keys -
wMbj6ajWbic[254][0]
BvYR0L6f2Ig[108][0]
2iD-tVS8NPw[443][0]
2WGyTLYerpo[391][0]
OQvJTdtJ2H4[88][0]
wMbj6ajWbic[658][0]

There are 33000 such keys

what do these dimensions - [254][0] , [108][0] etc in front of the video id represent?

2. Is this aligned data suitable for implementing "multimodal sentiment analysis with RL"?

Also why is the audio feature vector of length 1585 after alignment?

Thanks!

**Comment by A2Zadeh** [comment]
@kushagrajain11 can you share the actual code? I think your sudo code may be missing some information. As for what the 254 and 0 mean, it means the 254th based on the first alignment and 0th based on the second alignment. 

The audio features used in RL paper is the COVAREP. You can discard the one that has 1585. That is OpenSmile.

**Comment by kushagrajain11** [comment]
@A2Zadeh looks like I was aligning the data incorrectly. After proper alignment now I have 2198 sequences and each sequence has a number of words, and same number of audio and video feature vectors.

I also tried contacting Minghai Chen on the email mentioned in the paper, but I think that email id is no longer active. Is there any other way I can contact him?

Also, were you able to get the code for the RL paper?
Thanks

**Comment by kushagrajain11** [comment]
@A2Zadeh any update on the code?
Thanks

**Comment by A2Zadeh** [comment]
@kushagrajain11 still waiting on a response. I will also look in our drives to see if I can find it.

**Comment by crystalhu** [comment]
@kushagrajain11  hello, do you have any code for paper <Multimodal Sentiment Analysis with Word-Level Fusion and Reinforcement Learning>?? I will make a project about multimodal emotion recognition, and I want to publish a paper  for  my doctor application as soon as possible. so now I  want to reproduce the paper, if you have the paper code,  can you send me a copy? thank you very much!!!

**Comment by A2Zadeh** [comment]
@crystalhu Unfortunately, I have not received any response from the author of the code even though I have pinged him several times. Since this is not a paper I am a first author of, I don't have access to the code. The author is Minghai Chen who used to be a student working with me. I will ping him again today and will update you if anything happens.

**Comment by crystalhu** [comment]
I am very glad to receive your email so soon. Thank you very much for the information you provided to me. I plan to contact Minghai Chen again, hoping for a good result. If you have any progress, please send me mail at any time. Thanks again!




------------------ 原始邮件 ------------------
发件人: "Amir Zadeh"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 凌晨0:04
收件人: "A2Zadeh/CMU-MultimodalSDK"<CMU-MultimodalSDK@noreply.github.com>;
抄送: "focus（笃定）"<2675167909@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [A2Zadeh/CMU-MultimodalSDK] Code for multimodal sentimentanalysis with RL (#60)




@crystalhu Unfortunately, I have not received any response from the author of the code even though I have pinged him several times. Since this is not a paper I am a first author of, I don't have access to the code. The author is Minghai Chen who used to be a student working with me. I will ping him again today and will update you if anything happens.

**Comment by A2Zadeh** [comment]
Folks, I was finally able to get my hands on the code. Again apologies, as I was not the first author, it was hard to track down the code after first author graduated. The code can be found here: https://drive.google.com/file/d/1_tnAUf9o2RGq2e5yOCT8cqIElOSKwiBh/view?usp=sharing
