### ISSUE TITLE
Metadata - country/location, topic, gender, etc

### ISSUE THREAD

**Issue by rosannamilner** [A2Zadeh/CMU-MultimodalSDK#64]
Hi @A2Zadeh , I'm looking for additional information about the data such as country/location, topic, gender, etc (last two both mentioned in papers) for every video but I'm not sure where to find it. Is it included in the dataset somewhere or can you point me in the right direction to find it please?

**Comment by A2Zadeh** [comment]
We can certainly provide that information. I just add it as a new step for future releases. 
https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/next_steps.md

**Comment by rosannamilner** [comment]
Great, look forward to it, thank you very much!

**Comment by A2Zadeh** [comment]
@rosannamilner what format would you prefer for this data? I can provide the JSON for the information from the YouTube API. Also for gender please refer to https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/72#issuecomment-449114411.

**Comment by MichaelGrundie** [comment]
Hi guys

I was also interested on gender labels and noticed the gender column in those label csvs are all 0

**Comment by MichaelGrundie** [comment]
Hi @A2Zadeh 

I am also interested in gender labels so that I can balance my test/train split. I checked out the comment #72 above but noticed all records have a gender value of 0.

In relation to your paper, I read 'Furthermore, we balance the gender in the dataset using the data provided by the judges (57% male to 43% female).'  Is this to say that 500 identities are male and the other 500 are female. Or that the chosen statements are balanced  50/50?

Thanks for your good work

**Comment by KuzmaNg** [comment]
Hi @rosannamilner ,
Have you got the additional infos for gender/topic in MOSEI? I have been following this issue for a while😫. 
Thank you.

**Comment by rosannamilner** [comment]
No sorry I don't have them, I'm also still waiting for all the metadata (and it's still listed as a small update on their todo list above). 

@A2Zadeh, do you have an idea of when these might be available? Thank you!

**Comment by KuzmaNg** [comment]
Thank you, @rosannamilner 
Yeah, I saw it on the nextstep list. Keep waiting.😂

**Comment by A2Zadeh** [comment]
Hello @rosannamilner @MichaelGrundie @KuzmaNg 

Yeah it's taking us a long time because currently we are busy preparing new computational sequences among other stuff such as preparing tutorials on how to build models. I just asked one of my students to get all the meta data and he said by Sunday that information will be available.

For gender, I remember what happened that all the fields are zeros. For MTurk we cannot do any annotations related to the subject due to IRB constraints. Therefore, we have our own internal annotations for gender. Let me look around and see what comes up. 

In the meantime, gender annotations should not take a lot of time, all you really need is one frame from each video (since they are monologues). It's not the easy solution, but it is a solution that you will have my gratitude for :). If you do so, please share with us the gender info with us as well.

Thank you!

**Comment by A2Zadeh** [comment]
Hello again @rosannamilner @MichaelGrundie @KuzmaNg,

Got some news for you. I actually have the information for gender in the supplementary material of the CMU-MOSEI paper, the only thing is we split it based on the channel not video. Is this information helpful? Otherwise, we will have to dig in more.

Best,

Amir

**Comment by MichaelGrundie** [comment]
Thanks for the update. I did look for the supplementary paper before but I can only come up with this dead link.

http://www.cs.cmu.edu/~pliang/papers/acl2018-mosei-supplementary-camera.pdf

**Comment by KuzmaNg** [comment]
Thanks. @A2Zadeh  
Gonna look into it.

**Comment by A2Zadeh** [comment]
Hello @rosannamilner @MichaelGrundie @KuzmaNg,

Just to give you an update on this, I am zipping the MOSEI with the metadata information, I will update the raw files once that is done. I still haven't been able to locate the information we have for gender. I will keep looking for that information.

**Comment by A2Zadeh** [comment]
Hello @rosannamilner @MichaelGrundie @KuzmaNg, 

CMU-MOSEI raw dataset is now updated with all the metadata for train, test and validation. Few videos You-Tube API failed to fetch metadata. There should however be a lot of videos in the added set to establish studies. Let me know how else I can help.

**Comment by A2Zadeh** [comment]
I assume this issue was resolved, so I am closing it. Please feel free to open it again, or email me if there were questions.
