### ISSUE TITLE
multiple tags and not ordered sequences

### ISSUE THREAD

**Issue by vickyzayats** [A2Zadeh/CMU-MultimodalSDK#66]
Hi. I have noticed 2 issues with the current release:

1. After aligning, the features are in incorrect order (according to the intervals). The problem is in the dataset.py in __intersect_and_copy, in line 170. When you are trying to find all the subsequences of the video frame, if there are more than 1 (in case of two alignments happening one after each other), it would find all the alignments in unsorted order. As a results the features and intervals are unsorted and can be repeated multiple times. 

2. Another problem is getting multiple labels for the same element. This happens when you call intersect on the labels (assuming you aligning according to the labels). In the data there are some overlaps between labels intervals. this would cause that for one label interval intersect is finding multiple regions in labels that correspond to that region in time, which results in >1 number of labels (I was experimenting with Sentiment Labels only).

Thanks!

**Comment by vickyzayats** [comment]
Regarding the first one, you should just order the segments in line 165 in dataset.py according to the keys in brackets instead of just getting all the keys:

relevant_entries=[x for x in sub_compseq.data.keys() if x.split('[')[0]==ref_entry_key.split('[')[0]]

There are multiple ways of doing so. For example, if you have a collection of keys ('12345[1][2]','12345[0][0]','12345[1][0]','12345[1][1]') you want first to order them by the number in the first brackets, and then by the number in the second bracket, so you get ('12345[0][0]','12345[1][0]','12345[1][1]','12345[1][2]'). Basically, you need just extra ordering in addition to getting all the keys that start with '12345'
 
I played around with MOSEI only, I am not sure if MOSI has the same problem with the tags. Regarding this issue, I am not quite sure if the words that on the boundaries of those problematic segments, should I ignore them or use them. I guess my question is if you know why there are overlaps in the boundaries of labels in the original data to begin with?

Thanks!

**Comment by A2Zadeh** [comment]
Thanks for the suggestions @vickyzayats. I think there is a good functionality to be added to get an ordered version of the dictionary, since dicts are unordered in python. Now, is the segments completely wrongly numbered? Because that shouldn't be the case. If we align a '12345' with 10 label annotations in that id, it should become `12345[0...9]`. Inside the bracket is the interval coming from the labels. So basically 12345[0] means part of 12345 video which intersects with [s0,e0] beginning and end of intervals 0. So that actually has nothing to do with the dict being ordered or unordered. The [i] comes from row number in intervals which is a 2D matrix. It is however, a desirable function to have things viewed in order. Am I correct?

Let me look into the overlap. I think if you remove the padding of 0.25 seconds from beginning and end, you get nonoverlapping segments. I am not sure about the 0.25, it could be 0.5. You may see from the labels. I actually wanna remove the padding. Caused more issues than solving anything. 

Thanks for raising the issues. Allow me some time to be able to fix them.

**Comment by vickyzayats** [comment]
I don't remember if they are or are not ordered completely, but even if they are ordered, they are ordered by string, which will put 12345[10] before 12345[2].  It would be great to have them in order since people can assume that they can just use the processed data as is, without much processing (e.g. you need to order the data anyways if you want to apply any sort of sequential model). Thanks for taking care of those issues!

**Comment by A2Zadeh** [comment]
@vickyzayats The indices are correct but not ordered. Good functionality though. I will change things to ordered dict and see what happens. Thanks for raising this concern. Please be in touch if you had any other issues.
