### ISSUE TITLE
Question about align function

### ISSUE THREAD

**Issue by stdoo** [A2Zadeh/CMU-MultimodalSDK#80]
Hi, I'm  confused about `__intersect_and_copy`, which is called in align function. Concretely, I don't understand the statements:
 ```
ref_copy = ref.copy()
 ref_copy[1] = -ref_copy[1]  # negative
 ref_copy = ref_copy[::-1]  # reverse
sub_copy = sub.copy()
sub_copy[:, 0] = -sub_copy[:, 0]
where_intersect = (numpy.all((sub_copy - ref_copy) > (-epsilon), axis=1) == True)
```
It seems like you are searching some intervals in other computational sequence close to the reference(Opinion label) interval, so that these intervals can have the same sentiment label. But what's the point of the negative and reverse operations? Why not just get the absolute value of `sub - ref`?

**Comment by A2Zadeh** [comment]
@stdoo the reason for that negation and inversion is to find whether or not the two timestamps overlap (overlap, as opposed to being close). Let's say you have intervals _a_ and _b_. If the beginning of _a_ (or _b_) is before the end of the _b_ (or _a_), AND the end of _a_ (or _b_) is after beginning of _b_ (or _a_) then we have an intersection. So both of the following need to be true - forgive my bad sudo code :)

```
end (b)-start (a) >0 
&&
end(a)-start (b)>0 

```
Let's say you have one modality that goes in the range (ref) [0.2, 0.5] and another modality that goes between (sub) [0.4, 0.6]. By end of line 5 ref=[-0.5,0.2], and sub=[-0.4,0.6], hence sub-ref=[0.1,0.4]. 

On a side note, I think I could have saved a line there and do the same things with one less negation. I am not going to fix it now since one negation really does not have a substantial computational cost. I might fix it in later versions.

**Comment by stdoo** [comment]
@A2Zadeh Very clear. Thanks a lot. But I can't figure out how to do it with one less negation and the `==True` in line 6 seems to be unnecessary. :)

**Comment by A2Zadeh** [comment]
@stdoo yup that ==True is to just remind myself when I move the code to torch for alignment. GPU does not output boolean. The way to do one less negation is through ref-sub as opposed to sub-ref, then you can save some negations from the lines above it.

**Comment by stdoo** [comment]
@A2Zadeh Thanks. Look forward to the later versions.
