### ISSUE TITLE
CMU-MOSEI missing presence-of-emotion labels

### ISSUE THREAD

**Issue by shelm** [A2Zadeh/CMU-MultimodalSDK#82]
Hi, 

I am currently trying to download the raw data of the CMU-MOSEI dataset including the labels. 
Since  I couldn't find the csd-files in the raw data I downloaded those via the sdk using the following code snippet:

`cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.labels,'cmumosei/')
`

However this seems to be working fine for the sentiment-labels and the Ekman emotions but it does not download the annotated presence-of-emotion, which is described in the paper. Is there any way to get access to those annotations?

**Comment by shelm** [comment]
Never mind. I misunderstood the description in the paper :)

**Comment by A2Zadeh** [comment]
@shelm We simply say if the average emotion is higher than 0, then emotion is present. Is it the best way? probably not but there is really no best way since no one has done the psychological studies to say where the cut should be. It's just a measure. I personally like to focus on MSE and correlation. Much better and easier to use. Let me know if this answers your question :)

**Comment by A2Zadeh** [comment]
@shelm You are welcome Dominik! Let us know if you had any other questions.
