### ISSUE TITLE
questions about MOSEI dataset

### ISSUE THREAD

**Issue by Beardlessape** [A2Zadeh/CMU-MultimodalSDK#95]
I change the code in readme to align the MOSEI dataset
the code as follow
`
def myavg(intervals,features):
        return numpy.average(features,axis=0)

cmumosei_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.highlevel,'cmumosei/')
cmumosei_highlevel.align('glove_vectors',collapse_functions=[myavg])
cmumosei_highlevel.add_computational_sequences(mmdatasdk.cmu_mosei.labels,'cmumosei/')
cmumosei_highlevel.align('Sentiment Labels')
cmumosei_highlevel.align('Emotion Labels')`

but the process will comes to the error like bellows when aligning the 'Emotion Labels'

<Warning>: The dataset does not have unified entry ids across computational sequences. Please call intersect first ...
File "/CMU-MultimodalSDK-master/mmsdk/mmdatasdk/dataset/dataset.py", line 108, in align otherseq_key], epsilon)
File "/CMU-MultimodalSDK-master/mmsdk/mmdatasdk/dataset/dataset.py", line 166, in __intersect_and_copy
	sub=numpy.concatenate([sub_compseq.data[x]["intervals"] for x in relevant_entries],axis=0)
ValueError: need at least one array to concatenate

However it works if I just align Sentiment Labels or Emotion Labels

**Comment by A2Zadeh** [comment]
Hello @Beardlessape. Technically you shouldn't get an error, but at the same time there is a logical problem in aligning to both sentiment and emotions. When I was building the SDK, the consensus was that experiments for sentiment and emotions will be different. Meaning that you will have a code that aligns to sentiment and another one to emotions. That being said, I think I should change the SDK to have both the sentiment and emotion labels in one csd file so this will be solved. It will take me a few days to make that change because that will require some extra steps such as clarifying what each dimension is for our features.
